# Generated by Django 6.0.2 on 2026-02-04 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BurnRatePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.DateField()),
                ('daily_average_spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projected_month_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_exhaustion_date', models.DateField(blank=True, null=True)),
                ('will_overspend', models.BooleanField(default=False)),
                ('overspend_percentage', models.FloatField(default=0)),
                ('savings_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burn_rate_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_month'],
            },
        ),
        migrations.CreateModel(
            name='SpendingPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.CharField(choices=[('planner', 'Planner'), ('impulse_spender', 'Impulse Spender'), ('minimalist', 'Minimalist'), ('balanced', 'Balanced')], max_length=20)),
                ('variance_score', models.FloatField(default=0)),
                ('category_diversity', models.FloatField(default=0)),
                ('weekend_vs_weekday_ratio', models.FloatField(default=0)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spending_personality', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_analyzed'],
            },
        ),
        migrations.CreateModel(
            name='WhatIfSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('adjustments', models.JSONField()),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('simulated_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('stressed', 'Stressed')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='tracker_exp_user_id_899117_idx'), models.Index(fields=['user', 'category'], name='tracker_exp_user_id_224b72_idx')],
            },
        ),
        migrations.CreateModel(
            name='MoneyLeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('monthly_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_count', models.IntegerField()),
                ('average_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency_description', models.CharField(max_length=100)),
                ('month', models.DateField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_leaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-monthly_total'],
                'unique_together': {('user', 'category', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('narrative', models.TextField()),
                ('top_category', models.CharField(max_length=50)),
                ('top_category_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_vs_actual', models.CharField(max_length=100)),
                ('emotional_trend', models.CharField(max_length=100)),
                ('money_leak_alerts', models.JSONField(blank=True, default=list)),
                ('key_insights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('average_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frequency', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'mood', 'category', 'period')},
            },
        ),
    ]
