# Generated by Django 4.2 on 2026-02-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_budget_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='leak_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
